import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/utils/ThemeProvider";
import { TailwindIndicator } from "@/components/utils/TailwindIndicator";
import { TRPCReactProvider } from "@/trpc/react";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TRPCReactProvider headers={headers()}>
          {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
          {children}
          {/* <Toaster />
            <TailwindIndicator />
          </ThemeProvider> */}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
